/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Biblioteca;
import BackEnd.Libro;
import javax.swing.JOptionPane;

/**
 * Ventana principal del sistema de gestión de biblioteca.
 * Sustituye al menú de consola: cada botón llama a un método de la clase Biblioteca.
 *
 * @author Alexander
 */
public class TestBiblioteca extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TestBiblioteca.class.getName());

    /**
     * Objeto del modelo. Vale null mientras el usuario no haya creado la biblioteca.
     */
    private Biblioteca biblioteca;

    /**
     * Creates new form TestBiblioteca
     */
    public TestBiblioteca() {
        initComponents();
        mostrarMensaje("Bienvenido al sistema de gestión de biblioteca.\n"
                + "Pulsa \"Crear biblioteca\" para comenzar.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        pnlOpciones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMostrarIndice = new javax.swing.JButton();
        btnDestruir = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlDatos = new javax.swing.JPanel();
        lblTituloLibro = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lblAutor = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        lblAnio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lblIndice = new javax.swing.JLabel();
        txtIndice = new javax.swing.JTextField();
        pnlResultados = new javax.swing.JPanel();
        scrResultados = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gestión de Biblioteca");
        setResizable(false);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Sistema de Gestión de Biblioteca");

        pnlOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnCrear.setText("Crear biblioteca");
        btnCrear.addActionListener(this::btnCrearActionPerformed);

        btnMostrar.setText("Mostrar libros");
        btnMostrar.addActionListener(this::btnMostrarActionPerformed);

        btnAgregar.setText("Agregar libro");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        btnModificar.setText("Modificar libro");
        btnModificar.addActionListener(this::btnModificarActionPerformed);

        btnEliminar.setText("Eliminar libro");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        btnMostrarIndice.setText("Mostrar por índice");
        btnMostrarIndice.addActionListener(this::btnMostrarIndiceActionPerformed);

        btnDestruir.setText("Destruir biblioteca");
        btnDestruir.addActionListener(this::btnDestruirActionPerformed);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout pnlOpcionesLayout = new javax.swing.GroupLayout(pnlOpciones);
        pnlOpciones.setLayout(pnlOpcionesLayout);
        pnlOpcionesLayout.setHorizontalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarIndice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDestruir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOpcionesLayout.setVerticalGroup(
            pnlOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCrear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMostrarIndice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDestruir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del libro"));

        lblTituloLibro.setText("Título:");
        lblAutor.setText("Autor:");
        lblAnio.setText("Año de publicación:");
        lblIndice.setText("Índice:");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloLibro)
                    .addComponent(lblAutor)
                    .addComponent(lblAnio)
                    .addComponent(lblIndice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIndice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloLibro)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnio)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIndice)
                    .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlResultados.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        txtResultados.setColumns(20);
        txtResultados.setEditable(false);
        txtResultados.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        txtResultados.setLineWrap(true);
        txtResultados.setRows(5);
        txtResultados.setWrapStyleWord(true);
        scrResultados.setViewportView(txtResultados);

        javax.swing.GroupLayout pnlResultadosLayout = new javax.swing.GroupLayout(pnlResultados);
        pnlResultados.setLayout(pnlResultadosLayout);
        pnlResultadosLayout.setHorizontalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlResultadosLayout.setVerticalGroup(
            pnlResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ===================== EVENTOS DE LOS BOTONES =====================

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String entrada = JOptionPane.showInputDialog(this,
                "Capacidad de la biblioteca (número entero mayor que 0):",
                "Crear biblioteca", JOptionPane.QUESTION_MESSAGE);
        if (entrada == null) {
            return; // El usuario canceló el cuadro de diálogo
        }
        try {
            int capacidad = Integer.parseInt(entrada.trim());
            if (biblioteca != null && biblioteca.existe()) {
                int respuesta = JOptionPane.showConfirmDialog(this,
                        "Ya existe una biblioteca. Si continúas se perderán sus libros.\n¿Deseas crearla de nuevo?",
                        "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if (respuesta != JOptionPane.YES_OPTION) {
                    return;
                }
            }
            if (biblioteca == null) {
                biblioteca = new Biblioteca(capacidad);
            } else {
                biblioteca.crearBiblioteca(capacidad);
            }
            limpiarCampos();
            mostrarMensaje("Biblioteca creada correctamente con capacidad para " + capacidad + " libros.");
        } catch (NumberFormatException ex) {
            mostrarError("La capacidad debe ser un número entero. Valor recibido: \"" + entrada + "\".");
        } catch (IllegalArgumentException ex) {
            mostrarError(ex.getMessage());
        } catch (Exception ex) {
            mostrarErrorInesperado(ex);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if (!bibliotecaExiste()) {
            return;
        }
        try {
            mostrarMensaje(biblioteca.mostrarLibros());
        } catch (IllegalStateException ex) {
            mostrarError(ex.getMessage());
        } catch (Exception ex) {
            mostrarErrorInesperado(ex);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (!bibliotecaExiste()) {
            return;
        }
        try {
            Libro libro = leerLibro();
            int indice = leerIndice();
            biblioteca.agregarLibro(libro, indice);
            limpiarCampos();
            mostrarMensaje("Libro agregado correctamente en la posición " + indice + ":\n" + libro);
        } catch (IllegalArgumentException | IllegalStateException | IndexOutOfBoundsException ex) {
            mostrarError(ex.getMessage());
        } catch (Exception ex) {
            mostrarErrorInesperado(ex);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        if (!bibliotecaExiste()) {
            return;
        }
        try {
            int indice = leerIndice();
            Libro libro = leerLibro();
            biblioteca.modificarLibro(indice, libro);
            limpiarCampos();
            mostrarMensaje("Libro modificado correctamente en la posición " + indice + ":\n" + libro);
        } catch (IllegalArgumentException | IllegalStateException | IndexOutOfBoundsException ex) {
            mostrarError(ex.getMessage());
        } catch (Exception ex) {
            mostrarErrorInesperado(ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (!bibliotecaExiste()) {
            return;
        }
        try {
            int indice = leerIndice();
            Libro eliminado = biblioteca.mostrarLibroPorIndice(indice);
            biblioteca.eliminarLibro(indice);
            limpiarCampos();
            mostrarMensaje("Libro eliminado de la posición " + indice + ":\n" + eliminado);
        } catch (IllegalArgumentException | IllegalStateException | IndexOutOfBoundsException ex) {
            mostrarError(ex.getMessage());
        } catch (Exception ex) {
            mostrarErrorInesperado(ex);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMostrarIndiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarIndiceActionPerformed
        if (!bibliotecaExiste()) {
            return;
        }
        try {
            int indice = leerIndice();
            Libro libro = biblioteca.mostrarLibroPorIndice(indice);
            if (libro == null) {
                mostrarMensaje("La posición " + indice + " está vacía.");
            } else {
                // Se llenan los campos con los getters para facilitar una modificación posterior
                txtTitulo.setText(libro.getTitulo());
                txtAutor.setText(libro.getAutor());
                txtAnio.setText(String.valueOf(libro.getAnioPublicacion()));
                mostrarMensaje("Libro en la posición " + indice + ":\n" + libro);
            }
        } catch (IllegalArgumentException | IllegalStateException | IndexOutOfBoundsException ex) {
            mostrarError(ex.getMessage());
        } catch (Exception ex) {
            mostrarErrorInesperado(ex);
        }
    }//GEN-LAST:event_btnMostrarIndiceActionPerformed

    private void btnDestruirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestruirActionPerformed
        if (!bibliotecaExiste()) {
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog(this,
                "Se eliminarán todos los libros y la biblioteca dejará de existir.\n¿Deseas continuar?",
                "Destruir biblioteca", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (respuesta != JOptionPane.YES_OPTION) {
            return;
        }
        biblioteca.destruirBiblioteca();
        limpiarCampos();
        mostrarMensaje("La biblioteca fue destruida y se liberaron todas las referencias.\n"
                + "Pulsa \"Crear biblioteca\" para empezar de nuevo.");
    }//GEN-LAST:event_btnDestruirActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?",
                "Salir", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    // ===================== MÉTODOS AUXILIARES =====================

    /**
     * Verifica que la biblioteca haya sido creada (y no destruida) antes de operar.
     */
    private boolean bibliotecaExiste() {
        if (biblioteca == null || !biblioteca.existe()) {
            mostrarError("La biblioteca no ha sido creada. Pulsa \"Crear biblioteca\" primero.");
            return false;
        }
        return true;
    }

    /**
     * Lee los JTextField del libro, valida obligatoriedad y tipo de dato,
     * y construye el objeto Libro (el constructor valida el rango del año).
     */
    private Libro leerLibro() {
        String titulo = txtTitulo.getText().trim();
        String autor = txtAutor.getText().trim();
        String anioTexto = txtAnio.getText().trim();
        if (titulo.isEmpty()) {
            throw new IllegalArgumentException("El campo Título es obligatorio.");
        }
        if (autor.isEmpty()) {
            throw new IllegalArgumentException("El campo Autor es obligatorio.");
        }
        if (anioTexto.isEmpty()) {
            throw new IllegalArgumentException("El campo Año de publicación es obligatorio.");
        }
        try {
            return new Libro(titulo, autor, Integer.parseInt(anioTexto));
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("El año debe ser un número entero. Valor recibido: \"" + anioTexto + "\".");
        }
    }

    /**
     * Lee el índice desde su JTextField, validando obligatoriedad y tipo de dato.
     */
    private int leerIndice() {
        String indiceTexto = txtIndice.getText().trim();
        if (indiceTexto.isEmpty()) {
            throw new IllegalArgumentException("El campo Índice es obligatorio.");
        }
        try {
            return Integer.parseInt(indiceTexto);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("El índice debe ser un número entero. Valor recibido: \"" + indiceTexto + "\".");
        }
    }

    private void limpiarCampos() {
        txtTitulo.setText("");
        txtAutor.setText("");
        txtAnio.setText("");
        txtIndice.setText("");
    }

    private void mostrarMensaje(String mensaje) {
        txtResultados.setText(mensaje);
        txtResultados.setCaretPosition(0);
    }

    private void mostrarError(String mensaje) {
        mostrarMensaje("[ERROR] " + mensaje);
    }

    private void mostrarErrorInesperado(Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
        mostrarError("Ocurrió un error inesperado: " + ex);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TestBiblioteca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnDestruir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnMostrarIndice;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloLibro;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlOpciones;
    private javax.swing.JPanel pnlResultados;
    private javax.swing.JScrollPane scrResultados;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextArea txtResultados;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
